### ISSUE TITLE
netmask

### ISSUE THREAD

**Issue by justin-gerhardt** [yuvadm/cidr.xyz#1]
when setting the to 0 bits sets for the net mask (/0) net mask is displayed as 255.255.255.255(/32)

**Comment by yuvadm** [comment]
Pending upstream fix https://github.com/rs/node-netmask/issues/17

**Comment by yuvadm** [comment]
Upstream is already fixed and released. This can either be fixed standalone, or as part of #3

**Comment by yuvadm** [comment]
Fixed in #5
