### ISSUE TITLE
Incorrect range

### ISSUE THREAD

**Issue by oscar-b** [yuvadm/cidr.xyz#10]
Tested with `10.5.5.240/28`, which incorrectly gives: 

NETMASK: 255.255.255.240
FIRST IP: 10.5.5.241
LAST IP: 10.5.5.254
COUNT: 16

It should be: Start IP: 10.5.5.240 End IP: 10.5.5.255

**Comment by oscar-b** [comment]
Ah maybe this is an issue in the netmask package though: https://github.com/rs/node-netmask

**Comment by sensei-wu** [comment]
for a CIDR `10.0.0.0/30`, I get first `10.0.0.1` and last `10.0.0.2` instead of `10.0.0.0` and `10.0.0.3`. Could you please tell me why?

**Comment by yuvadm** [comment]
Exactly. node-netmask returns **usable** addresses, neglecting the base and broadcast addresses.

**Comment by yuvadm** [comment]
@mattkemp That's a pretty good idea! Would you like to open a PR with that change?
