### ISSUE TITLE
Feature request for IPv6 CIDR ranges

### ISSUE THREAD

**Issue by git4example** [yuvadm/cidr.xyz#32]
Please include feature to calculate and split IPv6 CIDR ranges.

**Comment by yuvadm** [comment]
Great idea! Do you have any thoughts on how to visualize IPv6 in a reasonable way?

**Comment by cremor** [comment]
See https://cidrv6.xyz and https://github.com/scorpil/cidrv6.xyz

**Comment by yuvadm** [comment]
This great I had no idea it existed, love it :laughing: @scorpil!

**Comment by Scorpil** [comment]
Glad you liked it @yuvadm 👍

**Comment by yuvadm** [comment]
@guysoft I generally agree. we could probably have cidr.xyz/v6 or something hosting the v6 version.

**Comment by yuvadm** [comment]
I'm going to close this for now, seems https://cidrv6.xyz/ has us covered, if we ever want to merge projects we can revisit in a PR.

**Comment by guysoft** [comment]
I guess @yuvadm you could link to them "in case you need ipv6 here you go"
