### ISSUE TITLE
Issue in corner cases

### ISSUE THREAD

**Issue by DeividJones** [yuvadm/cidr.xyz#37]
I was using your calculator and according to it the first usable IP for 10.88.135.145/28 (default value) is 10.88.135.145 when should be 10.88.135.144.
![image](https://user-images.githubusercontent.com/17201506/114417461-e8ab7700-9bb1-11eb-8a2e-26af4f727b1f.png)

Actually, if you use 10.88.135.145/28 as a input CIDR you retrieve 10.88.135.145 as a first usable IP.
![image](https://user-images.githubusercontent.com/17201506/114418030-6a9ba000-9bb2-11eb-8d01-71d2d198cefc.png)

I hope it help!

**Comment by yuvadm** [comment]
Thanks for the report @DeividJones , this is a duplicate of #28 and previously #10
