### ISSUE TITLE
Responsive view

### ISSUE THREAD

**Issue by yuvadm** [yuvadm/cidr.xyz#4]
The current view looks horrible on small devices. It could be great to have an interface that looks reasonable well on mobile / small screen devices.

**Comment by jibin2706** [comment]
@yuvadm Should I use flexbox?

**Comment by yuvadm** [comment]
@jibin2706 yeah why not, whatever works well.

**Comment by JimBledsoe** [comment]
I can see using two basic approaches, containers with flex and styling changes responsive to display size.

The input fields and bitmasks can scale down slightly and start trimming padding. They really only make sense displayed in their exact orientations.

The output ips can be neatly arranged in container sets to let them stack into two rows as needed.

The intro text is probably good as-is, but maybe could be trimmed a tiny bit for brevity.

What is the smallest size you are looking to support? Something like iPhone 6 or 7 in a non-SE size covers 5+ years.
