### ISSUE TITLE
Feature to load CIDR related info like CIDR Class 

### ISSUE THREAD

**Issue by parikshitataws** [yuvadm/cidr.xyz#49]
It would be more helpful to use UI realestate by showing some CIDR related information at the bottom as we type CIDR in the text box, bottom of the screen if you can dynamically load info about CIDR Class info, if any restrictions applicable for the specified CIDR ..etc

**Comment by yuvadm** [comment]
@parikshitataws could you please describe what kind of restrictions you had in mind here? Closing for now, please reopen with clarifications.
