### ISSUE TITLE
Unintuitive results for "first usable IP"

### ISSUE THREAD

**Issue by adamchalmers** [yuvadm/cidr.xyz#65]
Hi, first off, I love this website, thank you so much for making it. I use it to explain CIDRs to junior engineers or engineers without a networking background and it really helps them "get it".

For example the CIDR `200.88.135.144/4`, your calculator says the first IP is 192.0.0.1 

<img width="1141" alt="cidrs" src="https://user-images.githubusercontent.com/5407457/210678346-a9501870-7691-4a1b-99d4-aafe160ca781.png">

But I think the first IP address should be 192.0.0.0, as that is the lowest IP address that matches the `1,1,0,0` 4-bit prefix. Other CIDR calculators e.g. https://www.ipaddressguide.com/cidr or the Rust [ipnetwork crate](docs.rs/ipnetwork) agree with me.

<img width="863" alt="Screenshot 2023-01-05 at 12 03 11 PM" src="https://user-images.githubusercontent.com/5407457/210678563-59fd43b1-694a-490b-a020-c877ca2aeeea.png">

I see you're using the [NodeJS netmask package](https://www.npmjs.com/package/netmask) for calculating first/last IPs. So I guess the issue is in the library. According to [this great StackOverflow question](https://stackoverflow.com/questions/14915188/ip-address-ending-with-zero/14915309#14915309) it comes down to whether .0 IPs are really "usable" as some hardware reserves them for the "network ID" and doesn't consider them "real" IPs that devices can use. 

The only reason I bother to go into this much detail is that I frequently use your website for teaching purposes, and to help generate unit tests for code which deals with CIDRs. Maybe the UI could be updated to differentiate between the "usable" IPs and the IPs in the CIDR? I certainly found the differences between different IP calculator websites/libraries confusing.

**Comment by yuvadm** [comment]
Another idea that we can implement is that in edges cases like the one you mentioned, we can show a link to relevant discussions that further explain e.g. why .0 are or aren't valid IP addresses.

**Comment by adamchalmers** [comment]
I think for my use-case (teaching) the best outcome would be a UI that shows the full IP space and has a little note about the special broadcast and network IPs.

I'm not sure if that is easy to do in JS, or if the netmask library supports that. I've written code to calculate CIDRs in Rust that I could port over, if you're open to moving away from the netmask library?

**Comment by yuvadm** [comment]
I'll happily accept a PR that implements custom netmask/CIDR calculations

**Comment by JimBledsoe** [comment]
The netmask library already provides the base and broadcast addresses, which are the true first and last. PR headed your way....

![image](https://github.com/yuvadm/cidr.xyz/assets/16745916/af5eecb9-fa45-42ac-b2fa-0a6e770b2161)
