### ISSUE TITLE
Netlify CI / CD failing - Unsupported build image

### ISSUE THREAD

**Issue by aravindvnair99** [yuvadm/cidr.xyz#66]
Netlify removed support for Ubuntu 16.04 Xenial Xerus build image on 15th November 2022. Refer https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

@yuvadm can you please fix the same via https://app.netlify.com/sites/cidr/settings/deploys#build-image-selection ?

**Comment by yuvadm** [comment]
done

**Comment by aravindvnair99** [comment]
Thanks @yuvadm!

**Comment by aravindvnair99** [comment]
@yuvadm can you also trigger the deployments again?
