### ISSUE TITLE
HTTPS certificate invalid

### ISSUE THREAD

**Issue by matthias-busch** [yuvadm/cidr.xyz#79]
Hi there! 

First off: Thanks for creating this! With the help of your tool I finally understood CIDR blocks. :) 

But when I tried to use the tool, I was greeted with this today:
![issue](https://github.com/yuvadm/cidr.xyz/assets/89919599/3b630204-b45b-433e-841c-54ddd01cc300)

Seems like the site's certificate has become invalid:
![issue2](https://github.com/yuvadm/cidr.xyz/assets/89919599/1216740b-152c-40ab-8fb0-8e1923dce7e9)

**Comment by aravindvnair99** [comment]
@matthias-busch works fine for me and even via online tools I checked. Are you on a VPN or using custom DNS server by any chance? The certificate shown in your screenshot is not the right one.

Refer:
- https://mxtoolbox.com/SuperTool.aspx?action=https%3acidr.xyz&run=toolpage

- https://www.ssllabs.com/ssltest/analyze.html?d=cidr.xyz

**Comment by matthias-busch** [comment]
Sure enough, I was connected to a company VPN, works fine without it. My bad!

**Comment by aravindvnair99** [comment]
No problem, thanks for confirming @matthias-busch!
