### ISSUE TITLE
Feature request - CIDR input steper

### ISSUE THREAD

**Issue by warrenc5** [yuvadm/cidr.xyz#83]
Hi, this has become my favourite calculator.

The problem I'm trying to solve is what is the CIDR for this IP range 10.x-10.y as Network technicians typically are lazy and use - ranges instead of CIDR subnets - because they don't understand bitmasks in networking 101 or other reasons IDK.

If CIDR had a stepper that let me scroll down from 32->0 then I could check the end usable IP and know the CIDR ranges to give to real network engineers who aren't so lazy :)

**Comment by yuvadm** [comment]
Did you try scrolling up/down or using the up/down keys when the range octet is in focus?
