### ISSUE TITLE
Using dot key does not move focus on next input

### ISSUE THREAD

**Issue by Jaimer** [yuvadm/cidr.xyz#91]
Hi, before all I have to say this is a great simple tool that I use at least once a week.

Today I noticed it got upgraded and I'm used to type the IP address octets following with a dot (.) and this used to change the focus to the next input.

Now only works with tab key and of course mouse clic.

**Comment by yuvadm** [comment]
@Jaimer thanks for spotting this regression! Will push a fix soon.
