### ISSUE TITLE
Pasting an IP address no longer populates all input fields

### ISSUE THREAD

**Issue by JonathanStreet** [yuvadm/cidr.xyz#92]
I've noticed a difference in behaviour recently.

Previously I've been able to copy and paste an IP address into the octet fields and they've all been updated when pasting into the first field - populating the full IP address. The new behaviour is that only the selected field gets updated.

**Comment by yuvadm** [comment]
@JonathanStreet thanks for catching this, I was under the impression paste behavior never worked in the previous version before the redesign we launched a few days ago, but it appears I was wrong.

I'll get around to fixing this shortly.

**Comment by yuvadm** [comment]
@robinvalk yeah it's deployed and works e.g. when pasting `1.2.3.4/5`. Perhaps you're just pasting `1.2.3.4` without a mask? I could probably have it fall back to just changing the IP without the CIDR octet.

**Comment by yuvadm** [comment]
Pushed fa54511e77eeccd4be61cdbd36265ece4dd799dc that allows for partial pastes, let me know if this works for you or if there's another problem.
